
version: 2.0
jobs:
  Forza:
    docker:
      - image: ubuntu:jammy-20211029
    steps:
      - run: apt update && apt upgrade -y 
      - run: ln -fs /usr/share/zoneinfo/Asia/Kolkata /etc/localtime && date
      - run: apt install -f -y git bison flex libxml2 libssl-dev bc zip default-jre python2 python3 python3-pip wget curl cpio lld ccache
      - run: git clone --depth=1 https://github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME} -b ${CIRCLE_BRANCH} .
      - run: bash build.sh --azure --lld
workflows:
  version: 2
  build:
    jobs:
      - Forza
