on:
  push:
    branches: [ workflow ]
jobs:
  node-docker:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:jammy-20211029

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: apt update && apt upgrade -y
      - run: ln -fs /usr/share/zoneinfo/Asia/Kolkata /etc/localtime && date
      - run: apt install -f -y git bison flex libxml2 libssl-dev bc zip default-jre python2 python3 python3-pip wget curl cpio lld ccache
      - run: curl https://raw.githubusercontent.com/Abhishek001konni/scripts/main/build.sh -o build
      - run: bash build --atomx --lld
    env:
        token: ${{ secrets.TOKEN }}
        chat_id: ${{ secrets.CHAT_ID }}
